"""initial database

Revision ID: 71b7f9950c96
Revises: 804a742527f3
Create Date: 2025-04-28 15:29:19.052094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b7f9950c96'
down_revision: Union[str, None] = '804a742527f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('wait', 'in_progress')", name='valid_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('subsystem_name', sa.String(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_log_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_log_id', sa.String(), nullable=False),
    sa.Column('chat_message_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_log_id'], ['chat_log.id'], ),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_log_id', sa.String(), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_log_id'], ['chat_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_memory')
    op.drop_table('chat_log_entry')
    op.drop_table('chat_message')
    op.drop_table('chat_log')
    # ### end Alembic commands ###
